---
- name: Install Apache
  hosts: all
# become: yes
  
# vars:
#   source_file: ./website/index.html
#   destin_file: /var/www/htmp

  tasks:
# - name: Check and print linux version
#   debug: var=ansible_os_family

  - name: Install Apache RedHat
    yum: name=httpd state=latest

#      - name: Copy HomePage file to WebServer
#        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
#        notify: Restart Apache RedHat

  - name: Start Web Server service for RedHat
    service: name=httpd state=started enabled=yes
#   when: ansible_os_family == "RedHat"


  - name: Add firewall role
    command: firewall-cmd --zone=public --permanent --add-service=http
    command: firewall-cmd --zone=public --permanent --add-service=https
    command: firewall-cmd --reload
    
