---
- name: Install APK
  hosts: all
  become: yes
  
  vars:
    source_file: ./website/index.html
    destin_file: /var/www/htmp

  tasks:
  - name: Check and print linux version
    debug: var=ansible_os_family

  - block: #---------- for RedHat-------------------------- 

       - name: Install APK RedHat
         yum: name=httpd state=latest

       - name: Copy HomePage file to WebServer
         copy: src={{ source_file }} dest={{ destin_file }} mode=0555
         notify: Restart Apache RedHat

       - name: Start Web Server service for RedHat
         service: name=httpd state=started eneble=yes
    when: ansible_os_family == "RedHat"
#------------------------------------------------------------

  - block: #---------- for Debian-------------------------- 

       - name: Install APK Debian
         yum: name=apache2 state=latest

       - name: Copy HomePage file to WebServer
         copy: src={{ source_file }} dest={{ destin_file }} mode=0555
         notify: Restart Apache Debian

       - name: Start Web Server service for Debian
         service: name=apache2 state=started eneble=yes
    when: ansible_os_family == "Debian"
#------------------------------------------------------------

#-----------------FOR WEB SERVERS---------------------------------------
  - name: Add firewall role
    command: firewall-cmd --zone=public --permanent --add-service=http
    command: firewall-cmd --zone=public --permanent --add-service=https
    command: firewall-cmd --reload
#-----------------------------------------------------------------------