---
- name: qemu-guest-agent
  hosts: centos

  tasks:
  - name: Install qemu-guest-agent
    yum: name=qemu-guest-agent state=latest

  - name: Start qemu-guest-agent and enable it the every boot
    service: name=qemu-guest-agent state=started enabled=yes
