---
- name: Install qemu-guest-agent
  hosts: all
  become: yes

  tasks:
  - name: Check and print linux version
    debug: var=ansible_os_family

  - name: Install agent for RedHat
    yum: name=qemu-guest-agent state=latest #removed, absent, installed або latest     
    when: ansible_os_family == "RedHat"

  - name: Start agent and enable it the every boot
    service: name=qemu-guest-agent state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Install agent for Debian
    apt: name=qemu-guest-agent state=latest #removed, absent, installed або latest
    when: ansible_os_family == "Debian"

  - name: Start agent and enable it the every boot
    service: name=qemu-guest-agent state=started enabled=yes
    when: ansible_os_family == "Debian"
  