---
- name: qemu-guest-agent
  hosts: ubuntu
  become: yes
  become_method: su
  become_user: lex
  --ask-become-pass, -K

  tasks:
   - name: Install qemu-guest-agent
     apt: name=qemu-guest-agent state=present

   - name: Start qemu-guest-agent and enable it the every boot
     service: name=qemu-guest-agent state=started enabled=yes
