---
- name: variables-lesson
  hosts: all
# become: yes
  
  vars:
     message1  : Hello
     message2  : How are you?
         
  tasks:
  
  - name: Print message1  
    debug:
      var: message1
      var: message2  
        
  - debug:
      msg: "{{ message1 }} {{ owner }}. {{ message2 }}"

  - set_fact: full_message="{{ message1 }}, {{ message2 }}"

  - debug:
      var: full_message

  
 
