---
# tasks file for deploy_apache_web
- block: #----------------Block fot RedHat-----------------------------------
    - name: Install Apache for RedHat
      yum: name=httpd state=latest #removed, absent, installed або latest     
    - name: Start Apache and enable it the every boot
      command: systemctl enable httpd.service
      command: service httpd start
      

    - name: Add firewall role
      command: firewall-cmd --zone=public --permanent --add-service=http
      command: firewall-cmd --reload
  when: ansible_os_family == "RedHat"

- block: #----------------Block fot Debian-----------------------------------
    - name: Install Apache for Debian
      apt: name=apache2 state=latest #removed, absent, installed або latest     

    - name: Start Apache and enable it the every boot
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"
#------------------------------------------------------------------------------
- name: Generate index.html
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555

# - name: Copy HomePage to WebServer
#   copy: src={{ item }} dest={{ destin_folder }} mode=0555
#    with_fileglob: "{{ source_folder }}/*.*"
#--------------Можемо перерахувати файли поіменно------------------------------    
#   copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0555
#   loop:
#      - "index.html"
#      - "fon.png"
#------------------------------------------------------------------------------    

  notify: 
   - Restart Apache RedHat
   - Restart Apache Debian

